### ISSUE TITLE
Fails to build with GHC 9.2.1

### ISSUE THREAD

**Issue by dunrix** [vincenthz/cryptonite#355]
$ cabal install cryptonite-0.29

> [ 55 of 137] Compiling Crypto.Internal.WordArray ( Crypto/Internal/WordArray.hs, dist/build/Crypto/Internal/WordArray.o, dist/build/Crypto/Internal/WordArray.dyn_o )
> 
> Crypto/Internal/WordArray.hs:117:52: error:
>     • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
>     • In the third argument of ‘writeWord32Array#’, namely
>         ‘(be32Prim (indexWord32OffAddr# a i))’
>       In the expression:
>         writeWord32Array# mb i (be32Prim (indexWord32OffAddr# a i)) st
>       In an equation for ‘st'’:
>           !st'
>             = writeWord32Array# mb i (be32Prim (indexWord32OffAddr# a i)) st
>     |
> 117 |                 let !st' = writeWord32Array# mb i (be32Prim (indexWord32OffAddr# a i)) st
>     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> Crypto/Internal/WordArray.hs:117:62: error:
>     • Couldn't match expected type ‘Word#’ with actual type ‘Word32#’
>     • In the first argument of ‘be32Prim’, namely
>         ‘(indexWord32OffAddr# a i)’
>       In the third argument of ‘writeWord32Array#’, namely
>         ‘(be32Prim (indexWord32OffAddr# a i))’
>       In the expression:
>         writeWord32Array# mb i (be32Prim (indexWord32OffAddr# a i)) st
>     |
> 117 |                 let !st' = writeWord32Array# mb i (be32Prim (indexWord32OffAddr# a i)) st
>     |                                                              ^^^^^^^^^^^^^^^^^^^^^^^
> cabal: Failed to build cryptonite-0.29

    $ ghc --version
> The Glorious Glasgow Haskell Compilation System, version 9.2.1

    $ cabal --version
> cabal-install version 3.6.2.0
> compiled using version 3.6.2.0 of the Cabal library

**Comment by brandon-leapyear** [comment]
https://github.com/haskell-crypto/cryptonite/pull/354

**Comment by mouse07410** [comment]
As building with GHC-9.2.1 makes no sense now, here's what's happening with GHC-9.2.2:
```
$ cabal build -w ghc-9.2.2
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - basement-0.0.14 (lib) (requires build)
 - memory-0.17.0 (lib) (requires build)
 - cryptonite-0.30 (lib) (first run)
Starting     basement-0.0.14 (lib)
Building     basement-0.0.14 (lib)
Haddock      basement-0.0.14 (lib)
Installing   basement-0.0.14 (lib)
Completed    basement-0.0.14 (lib)
Starting     memory-0.17.0 (lib)
Building     memory-0.17.0 (lib)
Haddock      memory-0.17.0 (lib)
Installing   memory-0.17.0 (lib)
Completed    memory-0.17.0 (lib)
Configuring library for cryptonite-0.30..
Preprocessing library for cryptonite-0.30..
Building library for cryptonite-0.30..
[  1 of 137] Compiling Crypto.Cipher.DES.Primitive ( Crypto/Cipher/DES/Primitive.hs, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/build/Crypto/Cipher/DES/Primitive.o, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/build/Crypto/Cipher/DES/Primitive.dyn_o )
[  2 of 137] Compiling Crypto.Data.Padding ( Crypto/Data/Padding.hs, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/build/Crypto/Data/Padding.o, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/build/Crypto/Data/Padding.dyn_o )
.  .  .  .  .
[137 of 137] Compiling Crypto.Tutorial  ( Crypto/Tutorial.hs, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/build/Crypto/Tutorial.o, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/build/Crypto/Tutorial.dyn_o )
Preprocessing library for cryptonite-0.30..
Running Haddock on library for cryptonite-0.30..
 100% (  4 /  4) in 'Crypto.Data.Padding'
 100% (  8 /  8) in 'Crypto.Error'
 100% (  8 /  8) in 'Crypto.Hash.IO'
  92% ( 25 / 27) in 'Crypto.Cipher.Types'
  Missing documentation for:
    CCM_M (Crypto/Cipher/Types/Base.hs:45)
    CCM_L (Crypto/Cipher/Types/Base.hs:46)
  75% (  3 /  4) in 'Crypto.ConstructHash.MiyaguchiPreneel'
  Missing documentation for:
    MiyaguchiPreneel (Crypto/ConstructHash/MiyaguchiPreneel.hs:26)
   0% (  0 /  2) in 'Crypto.Cipher.Utils'
  Missing documentation for:
    Module header
    validateKeySize (Crypto/Cipher/Utils.hs:10)
 100% (  5 /  5) in 'Crypto.Cipher.TripleDES'
 100% (  2 /  2) in 'Crypto.Cipher.DES'
 100% (  5 /  5) in 'Crypto.Cipher.Salsa'
 100% (  6 /  6) in 'Crypto.Cipher.XSalsa'
 100% (  5 /  5) in 'Crypto.Cipher.RC4'
 100% (  9 /  9) in 'Crypto.Cipher.ChaCha'
 100% (  4 /  4) in 'Crypto.Cipher.AES'
Warning: 'bitlen' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'n' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
  95% ( 46 / 48) in 'Crypto.Hash.Algorithms'
  Missing documentation for:
    Blake2bp (Crypto/Hash/Blake2.hs:140)
    Blake2sp (Crypto/Hash/Blake2.hs:117)
 100% ( 23 / 23) in 'Crypto.Hash'
   0% (  0 /  4) in 'Crypto.Cipher.Twofish'
  Missing documentation for:
    Module header
    Twofish128 (Crypto/Cipher/Twofish.hs:11)
    Twofish192 (Crypto/Cipher/Twofish.hs:23)
    Twofish256 (Crypto/Cipher/Twofish.hs:35)
 100% (  2 /  2) in 'Crypto.Cipher.CAST5'
 100% (  6 /  6) in 'Crypto.Cipher.Blowfish'
 100% (  2 /  2) in 'Crypto.Cipher.Camellia'
Warning: 'hashIterations' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'hashParallelism' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'hashMemory' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
  80% (  8 / 10) in 'Crypto.KDF.Argon2'
  Missing documentation for:
    defaultOptions (Crypto/KDF/Argon2.hs:93)
    hash (Crypto/KDF/Argon2.hs:102)
  75% (  3 /  4) in 'Crypto.KDF.BCryptPBKDF'
  Missing documentation for:
    Parameters (Crypto/KDF/BCryptPBKDF.hs:41)
 100% (  4 /  4) in 'Crypto.MAC.CMAC'
Warning: 'hmacFinalize' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 10 / 10) in 'Crypto.MAC.HMAC'
  62% (  5 /  8) in 'Crypto.KDF.PBKDF2'
  Missing documentation for:
    fastPBKDF2_SHA1 (Crypto/KDF/PBKDF2.hs:110)
    fastPBKDF2_SHA256 (Crypto/KDF/PBKDF2.hs:125)
    fastPBKDF2_SHA512 (Crypto/KDF/PBKDF2.hs:140)
 100% (  3 /  3) in 'Crypto.KDF.Scrypt'
 100% (  5 /  5) in 'Crypto.KDF.HKDF'
 100% ( 10 / 10) in 'Crypto.MAC.KMAC'
  91% ( 11 / 12) in 'Crypto.MAC.Poly1305'
  Missing documentation for:
    authTag (Crypto/MAC/Poly1305.hs:52)
 100% ( 12 / 12) in 'Crypto.Cipher.ChaChaPoly1305'

Crypto/Number/Compat.hs:57:22: warning: [-Wdeprecations]
    In the use of ‘gcdExtInteger’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerGcde instead"
   |
57 |   where (# g, s #) = gcdExtInteger a b
   |                      ^^^^^^^^^^^^^

Crypto/Number/Compat.hs:90:40: warning: [-Wdeprecations]
    In the use of ‘powModInteger’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerPowMod# instead"
   |
90 | gmpPowModInteger b e m = GmpSupported (powModInteger b e m)
   |                                        ^^^^^^^^^^^^^

Crypto/Number/Compat.hs:101:13: warning: [-Wdeprecations]
    In the use of ‘recipModInteger’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerRecipMod# instead"
    |
101 |   where r = recipModInteger g m
    |             ^^^^^^^^^^^^^^^

Crypto/Number/Compat.hs:132:49: warning: [-Wdeprecations]
    In the use of ‘sizeInBaseInteger’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerSizeInBase# instead"
    |
132 | gmpSizeInBytes n = GmpSupported (I# (word2Int# (sizeInBaseInteger n 256#)))
    |                                                 ^^^^^^^^^^^^^^^^^

Crypto/Number/Compat.hs:140:48: warning: [-Wdeprecations]
    In the use of ‘sizeInBaseInteger’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerSizeInBase# instead"
    |
140 | gmpSizeInBits n = GmpSupported (I# (word2Int# (sizeInBaseInteger n 2#)))
    |                                                ^^^^^^^^^^^^^^^^^

Crypto/Number/Compat.hs:149:10: warning: [-Wdeprecations]
    In the use of ‘exportIntegerToAddr’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerToAddr# instead"
    |
149 |     _ <- exportIntegerToAddr n addr 1#
    |          ^^^^^^^^^^^^^^^^^^^

Crypto/Number/Compat.hs:163:10: warning: [-Wdeprecations]
    In the use of ‘exportIntegerToAddr’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerToAddr# instead"
    |
163 |     _ <- exportIntegerToAddr n addr 0#
    |          ^^^^^^^^^^^^^^^^^^^

Crypto/Number/Compat.hs:177:5: warning: [-Wdeprecations]
    In the use of ‘importIntegerFromAddr’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerFromAddr# instead"
    |
177 |     importIntegerFromAddr addr (int2Word# n) 1#
    |     ^^^^^^^^^^^^^^^^^^^^^

Crypto/Number/Compat.hs:189:5: warning: [-Wdeprecations]
    In the use of ‘importIntegerFromAddr’
    (imported from GHC.Integer.GMP.Internals):
    Deprecated: "Use integerFromAddr# instead"
    |
189 |     importIntegerFromAddr addr (int2Word# n) 0#
    |     ^^^^^^^^^^^^^^^^^^^^^
Warning: 'a' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'b' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% (  8 /  8) in 'Crypto.Number.Basic'
Warning: 'm' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 11 / 11) in 'Crypto.Number.F2m'
 100% ( 11 / 11) in 'Crypto.Number.ModArithmetic'
 100% (  7 /  7) in 'Crypto.Number.Nat'
 100% (  4 /  4) in 'Crypto.Number.Serialize.Internal'
 100% (  5 /  5) in 'Crypto.Number.Serialize'
 100% (  4 /  4) in 'Crypto.Number.Serialize.Internal.LE'
 100% (  5 /  5) in 'Crypto.Number.Serialize.LE'
  75% (  9 / 12) in 'Crypto.OTP'
  Missing documentation for:
    hotp (Crypto/OTP.hs:66)
    TOTPParams (Crypto/OTP.hs:123)
    ClockSkew (Crypto/OTP.hs:125)
 100% ( 15 / 15) in 'Crypto.PubKey.ECC.Types'
 100% (  3 /  3) in 'Crypto.PubKey.MaskGenFunction'
 100% ( 11 / 11) in 'Crypto.PubKey.RSA.Types'
 100% (  5 /  5) in 'Crypto.PubKey.RSA.Prim'
 100% (  5 /  5) in 'Crypto.Random.Entropy.Unsafe'
 100% (  2 /  2) in 'Crypto.Random.Entropy'
 100% (  5 /  5) in 'Crypto.Random.EntropyPool'
 100% (  5 /  5) in 'Crypto.Random.Types'
  95% ( 20 / 21) in 'Crypto.Random'
  Missing documentation for:
    Seed (Crypto/Random.hs:43)
 100% ( 17 / 17) in 'Crypto.PubKey.Ed448'
 100% ( 17 / 17) in 'Crypto.PubKey.Ed25519'
 100% ( 34 / 34) in 'Crypto.PubKey.ECC.P256'
 100% ( 12 / 12) in 'Crypto.PubKey.Curve448'
 100% ( 12 / 12) in 'Crypto.PubKey.Curve25519'
 100% (  5 /  5) in 'Crypto.KDF.BCrypt'
 100% ( 21 / 21) in 'Crypto.ECC.Edwards25519'
 100% (  6 /  6) in 'Crypto.Cipher.AESGCMSIV'
 100% (  5 /  5) in 'Crypto.Number.Generate'
 100% ( 10 / 10) in 'Crypto.PubKey.ECC.Prim'
 100% ( 15 / 15) in 'Crypto.PubKey.ECC.ECDSA'
 100% (  3 /  3) in 'Crypto.PubKey.ECC.Generate'
 100% ( 19 / 19) in 'Crypto.PubKey.DSA'
 100% ( 10 / 10) in 'Crypto.Number.Prime'
 100% (  3 /  3) in 'Crypto.PubKey.Rabin.Types'
 100% (  5 /  5) in 'Crypto.PubKey.Rabin.OAEP'
 100% (  9 /  9) in 'Crypto.PubKey.Rabin.RW'
 100% (  6 /  6) in 'Crypto.PubKey.Rabin.Modified'
 100% ( 11 / 11) in 'Crypto.PubKey.Rabin.Basic'
Warning: 'e' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% (  9 /  9) in 'Crypto.PubKey.RSA'
 100% ( 13 / 13) in 'Crypto.PubKey.RSA.PSS'
 100% ( 15 / 15) in 'Crypto.PubKey.RSA.PKCS15'
 100% (  9 /  9) in 'Crypto.PubKey.RSA.OAEP'
 100% ( 10 / 10) in 'Crypto.PubKey.DH'
 100% (  8 /  8) in 'Crypto.PubKey.ECC.DH'
  23% (  3 / 13) in 'Crypto.ECC'
  Missing documentation for:
    Curve_P384R1 (Crypto/ECC.hs:195)
    Curve_P521R1 (Crypto/ECC.hs:229)
    Curve_X25519 (Crypto/ECC.hs:263)
    Curve_X448 (Crypto/ECC.hs:282)
    Curve_Edwards25519 (Crypto/ECC.hs:301)
    EllipticCurve (Crypto/ECC.hs:59)
    EllipticCurveDH (Crypto/ECC.hs:82)
    EllipticCurveArith (Crypto/ECC.hs:105)
    EllipticCurveBasepointArith (Crypto/ECC.hs:118)
    SharedSecret (Crypto/ECC.hs:56)
 100% ( 22 / 22) in 'Crypto.PubKey.EdDSA'
 100% (  3 /  3) in 'Crypto.PubKey.ECIES'
 100% ( 22 / 22) in 'Crypto.PubKey.ECDSA'
 100% (  3 /  3) in 'Crypto.Data.AFIS'
 100% (  3 /  3) in 'Crypto.System.CPU'
 100% (  9 /  9) in 'Crypto.Tutorial'
Warning: Crypto.Hash.Algorithms: could not find link destinations for:

	- Crypto.Hash.Types.hashInternalFinalizePrefix
	- Crypto.PubKey.RSA.PKCS15.hashDigestASN1
	- Crypto.Hash.SHAKE.cshakeInternalFinalize
	- Crypto.Hash.SHAKE.cshakeOutputLength
Warning: Crypto.MAC.KMAC: could not find link destinations for:

	- Crypto.Hash.SHAKE.cshakeInternalFinalize
	- Crypto.Hash.SHAKE.cshakeOutputLength
Warning: Crypto.Number.ModArithmetic: could not find link destinations for:

	- Crypto.Number.ModArithmetic.CoprimesAssertionError
	- Crypto.Number.ModArithmetic.ModulusAssertionError
Warning: Crypto.Number.Nat: could not find link destinations for:

	- Crypto.Internal.Nat.IsDiv8
	- Crypto.Internal.Nat.IsLE
	- Crypto.Internal.Nat.IsGE
Warning: Crypto.PubKey.Rabin.Types: could not find link destinations for:

	- Crypto.PubKey.Rabin.Types.PrimeCondition
Warning: Crypto.PubKey.RSA.PKCS15: could not find link destinations for:

	- Crypto.PubKey.RSA.PKCS15.hashDigestASN1
Warning: Crypto.ECC: could not find link destinations for:

	- Crypto.PubKey.EdDSA.hashWithDom
	- Crypto.Internal.Builder.Builder
	- Crypto.PubKey.EdDSA.pointPublic
	- Crypto.PubKey.EdDSA.publicPoint
	- Crypto.PubKey.EdDSA.encodeScalarLE
	- Crypto.PubKey.EdDSA.decodeScalarLE
	- Crypto.PubKey.EdDSA.scheduleSecret
Warning: Crypto.PubKey.EdDSA: could not find link destinations for:

	- Crypto.PubKey.EdDSA.hashWithDom
	- Crypto.Internal.Builder.Builder
	- Crypto.PubKey.EdDSA.pointPublic
	- Crypto.PubKey.EdDSA.publicPoint
	- Crypto.PubKey.EdDSA.encodeScalarLE
	- Crypto.PubKey.EdDSA.decodeScalarLE
	- Crypto.PubKey.EdDSA.scheduleSecret
Documentation created:
/Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/doc/html/cryptonite/cryptonite.txt
```

Build appears to succeed, with the above surprising messages - I'd appreciate if somebody could explain what's the implications of those.

Test passes:
```
$ cabal test -w ghc-9.2.2
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - clock-0.8.3 (lib) (requires build)
.  .  .  .  .
Configuring test suite 'test-cryptonite' for cryptonite-0.30..
Preprocessing test suite 'test-cryptonite' for cryptonite-0.30..
Building test suite 'test-cryptonite' for cryptonite-0.30..
[ 1 of 57] Compiling BCryptPBKDF      ( tests/BCryptPBKDF.hs, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/t/test-cryptonite/build/test-cryptonite/test-cryptonite-tmp/BCryptPBKDF.dyn_o )
[ 2 of 57] Compiling KAT_AES.KATCBC   ( tests/KAT_AES/KATCBC.hs, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/t/test-cryptonite/build/test-cryptonite/test-cryptonite-tmp/KAT_AES/KATCBC.dyn_o )
.  .  .  .  .
[57 of 57] Compiling Main             ( tests/Tests.hs, /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/t/test-cryptonite/build/test-cryptonite/test-cryptonite-tmp/Main.dyn_o )
Linking /Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/t/test-cryptonite/build/test-cryptonite/test-cryptonite ...
Running 1 test suites...
Test suite test-cryptonite: RUNNING...
Test suite test-cryptonite: PASS
Test suite logged to:
/Users/ur20980/src/cryptonite/dist-newstyle/build/x86_64-osx/ghc-9.2.2/cryptonite-0.30/t/test-cryptonite/test/cryptonite-0.30-test-cryptonite.log
1 of 1 test suites (1 of 1 test cases) passed.
```

**Comment by ysangkok** [comment]
This can be closed now that 0.30 is released.

**Comment by mouse07410** [comment]
I'm sure it can be closed, as it builds and passes the test. 

But it would be great if you could shed some light on the warning that build process generated, particularly those about inability to link...

**Comment by sjakobi** [comment]
I just encountered this build failure again. It would be great if v0.29 (and any other affected versions) would be revised with bounds `base < 4.16`, so `cabal` won't try to build them with GHC 9.2.
